FROM git.vst.lan/vst/tests:tox
MAINTAINER sergey.k@vstconsulting.net

RUN mkdir /tmp/polemarch
ADD . /tmp/polemarch/
RUN make rpm -C /tmp/polemarch/
RUN yum install /tmp/polemarch/dist/*.rpm -y
RUN cp -vf /tmp/polemarch/test_settings.ini /etc/polemarch/settings.ini && \
    sudo chown polemarch:polemarch /etc/polemarch/settings.ini && \
    sudo -H -u polemarch /opt/polemarch/bin/pip install -r /tmp/polemarch/requirements-test.txt && \
    cp -vf /tmp/polemarch/.coveragerc /home/polemarch/


# Run options
ENV DJANGO_DEBUG=true

ENTRYPOINT sudo -H -u polemarch /opt/polemarch/bin/polemarchctl test -v2 polemarch.main.tests
