FROM onegreyonewhite/tox:python

MAINTAINER sergey.k@vstconsulting.net

RUN mkdir /tmp/polemarch && \
    virtualenv /opt/polemarch
ADD . /tmp/polemarch/
RUN cd /tmp/polemarch && \
    tox -e build && \
    /opt/polemarch/bin/pip install /tmp/polemarch/dist/*.tar.gz && \
    rm -rf /tmp/polemarch/dist /tmp/polemarch/.tox && \
    mkdir -p /etc/polemarch/ && \
    cp -vf /tmp/polemarch/test_settings.ini /etc/polemarch/settings.ini

# Run options
ENV DJANGO_DEBUG=true
EXPOSE 8080

ENTRYPOINT /opt/polemarch/bin/polemarchctl webserver
