FROM onegreyonewhite/tox:centos

MAINTAINER sergey.k@vstconsulting.net

# Build and install rpm
COPY requirements-doc.txt /tmp/requirements-doc.txt
COPY requirements-git.txt /tmp/requirements-git.txt
COPY requirements.txt /tmp/requirements.txt
RUN pip2 install -U -r /tmp/requirements-doc.txt \
                    -r /tmp/requirements-git.txt \
                    -r /tmp/requirements.txt
RUN mkdir /tmp/polemarch
ADD . /tmp/polemarch/
RUN cd /tmp/polemarch && make rpm
RUN yum install /tmp/polemarch/dist/*.rpm -y
RUN cp -vf /tmp/polemarch/test_settings.ini /etc/polemarch/settings.ini


# Run options
ENV DJANGO_DEBUG=true
EXPOSE 8080

ENTRYPOINT sudo -u polemarch /opt/polemarch/bin/uwsgi /opt/polemarch/lib/python2.7/site-packages/polemarch/web.ini
