# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-18 03:16
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('main', '0002_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.AutoField(max_length=20, primary_key=True, serialize=False)),
                ('name', models.CharField(default=uuid.uuid1, max_length=512)),
            ],
            options={
                'default_related_name': 'groups',
            },
        ),
        migrations.CreateModel(
            name='Variable',
            fields=[
                ('id', models.AutoField(max_length=20, primary_key=True, serialize=False)),
                ('object_id', models.PositiveIntegerField()),
                ('key', models.CharField(max_length=128)),
                ('value', models.CharField(max_length=2048)),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.ContentType')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.RemoveField(
            model_name='scenario',
            name='parent',
        ),
        migrations.RemoveField(
            model_name='task',
            name='parent',
        ),
        migrations.AlterUniqueTogether(
            name='tasklist',
            unique_together=set([]),
        ),
        migrations.RemoveField(
            model_name='tasklist',
            name='scenario',
        ),
        migrations.RemoveField(
            model_name='tasklist',
            name='task',
        ),
        migrations.RemoveField(
            model_name='host',
            name='address',
        ),
        migrations.RemoveField(
            model_name='host',
            name='auth_data',
        ),
        migrations.RemoveField(
            model_name='host',
            name='auth_type',
        ),
        migrations.RemoveField(
            model_name='host',
            name='auth_user',
        ),
        migrations.RemoveField(
            model_name='host',
            name='group',
        ),
        migrations.RemoveField(
            model_name='host',
            name='nodeid',
        ),
        migrations.RemoveField(
            model_name='host',
            name='parent',
        ),
        migrations.AlterField(
            model_name='host',
            name='name',
            field=models.CharField(default=uuid.uuid1, max_length=512),
        ),
        migrations.DeleteModel(
            name='Scenario',
        ),
        migrations.DeleteModel(
            name='Task',
        ),
        migrations.DeleteModel(
            name='TaskList',
        ),
        migrations.AddField(
            model_name='group',
            name='hosts',
            field=models.ManyToManyField(related_name='groups', to='main.Host'),
        ),
        migrations.AddField(
            model_name='host',
            name='type',
            field=models.CharField(default='HOST', max_length=5),
        ),
    ]
