# Generated by Django 4.1.6 on 2023-02-15 00:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_v3_delete_old_models'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='task',
            options={'default_related_name': 'ansible_playbooks'},
        ),
        migrations.AlterField(
            model_name='task',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_query_name='ansible_playbooks', to='main.project'),
        ),
        migrations.AlterModelOptions(
            name='module',
            options={'default_related_name': 'ansible_modules'},
        ),
        migrations.AlterField(
            model_name='module',
            name='project',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_query_name='ansible_modules', to='main.project'),
        ),
        migrations.AddField(
            model_name='history',
            name='celery_task_id',
            field=models.UUIDField(null=True),
        ),
        migrations.RenameModel(
            old_name='Task',
            new_name='AnsiblePlaybook',
        ),
        migrations.RenameModel(
            old_name='ProjectTemplate',
            new_name='ProjectCommunityTemplate',
        ),
        migrations.AlterField(
            model_name='history',
            name='kind',
            field=models.CharField(db_index=True, default='ANSIBLE_PLAYBOOK', max_length=50),
        ),
    ]
