# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-21 05:10
from __future__ import unicode_literals

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_inventory'),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.AutoField(max_length=20, primary_key=True, serialize=False)),
                ('name', models.CharField(default=uuid.uuid1, max_length=256)),
                ('repository', models.CharField(max_length=512)),
                ('groups', models.ManyToManyField(blank=True, null=True, related_name='projects', to='main.Group')),
                ('hosts', models.ManyToManyField(blank=True, null=True, related_name='projects', to='main.Host')),
                ('inventories', models.ManyToManyField(blank=True, null=True, related_name='projects', to='main.Inventory')),
            ],
            options={
                'default_related_name': 'projects',
            },
        ),
    ]
