# -*- coding: utf-8 -*-
# Generated by Django 1.11.18 on 2019-02-13 05:05
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_projecttemplate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='history',
            name='executor',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='history', to=settings.AUTH_USER_MODEL),
        ),
    ]
