# Generated by Django 2.2 on 2019-04-02 04:04

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
from ..models import base


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_history_on_delete'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='periodictask',
            options={'default_related_name': 'periodic_task'},
        ),
        migrations.AlterModelOptions(
            name='task',
            options={'default_related_name': 'playbook'},
        ),
        migrations.AlterModelOptions(
            name='template',
            options={'default_related_name': 'template'},
        ),
        migrations.AlterField(
            model_name='group',
            name='owner',
            field=models.ForeignKey(default=base.first_staff_user, on_delete=django.db.models.deletion.SET_DEFAULT, related_name='polemarch_group_set', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='host',
            name='owner',
            field=models.ForeignKey(default=base.first_staff_user, on_delete=django.db.models.deletion.SET_DEFAULT, related_name='polemarch_host_set', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='inventory',
            name='owner',
            field=models.ForeignKey(default=base.first_staff_user, on_delete=django.db.models.deletion.SET_DEFAULT, related_name='polemarch_inventory_set', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='periodictask',
            name='owner',
            field=models.ForeignKey(default=base.first_staff_user, on_delete=django.db.models.deletion.SET_DEFAULT, related_name='polemarch_periodictask_set', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='project',
            name='owner',
            field=models.ForeignKey(default=base.first_staff_user, on_delete=django.db.models.deletion.SET_DEFAULT, related_name='polemarch_project_set', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='template',
            name='owner',
            field=models.ForeignKey(default=base.first_staff_user, on_delete=django.db.models.deletion.SET_DEFAULT, related_name='polemarch_template_set', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='usergroup',
            name='owner',
            field=models.ForeignKey(default=base.first_staff_user, on_delete=django.db.models.deletion.SET_DEFAULT, related_name='polemarch_usergroup_set', to=settings.AUTH_USER_MODEL),
        ),
    ]
