# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-24 08:14
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('main', '0005_project'),
    ]

    operations = [
        migrations.CreateModel(
            name='TypesPermissions',
            fields=[
                ('id', models.AutoField(max_length=20, primary_key=True, serialize=False)),
                ('groups', models.ManyToManyField(blank=True, null=True, related_name='related_objects', to='main.Group')),
                ('hosts', models.ManyToManyField(blank=True, null=True, related_name='related_objects', to='main.Host')),
                ('inventories', models.ManyToManyField(blank=True, null=True, related_name='related_objects', to='main.Inventory')),
            ],
            options={
                'default_related_name': 'related_objects',
            },
        ),
        migrations.AlterField(
            model_name='project',
            name='repository',
            field=models.CharField(max_length=2048),
        ),
        migrations.AddField(
            model_name='typespermissions',
            name='projects',
            field=models.ManyToManyField(blank=True, null=True, related_name='related_objects', to='main.Project'),
        ),
        migrations.AddField(
            model_name='typespermissions',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='related_objects', to=settings.AUTH_USER_MODEL),
        ),
    ]
