# Generated by Django 4.1.6 on 2023-03-05 11:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_v3_refactor_models'),
    ]

    operations = [
        migrations.CreateModel(
            name='InventoryState',
            fields=[
                ('id', models.AutoField(max_length=20, primary_key=True, serialize=False)),
                ('hidden', models.BooleanField(default=False)),
                ('data', models.JSONField(default=dict)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='inventory',
            name='plugin',
            field=models.CharField(default='POLEMARCH_DB', max_length=32, db_index=True),
        ),
        migrations.AddField(
            model_name='inventory',
            name='_inventory_state',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to='main.inventorystate'),
        ),
        migrations.RemoveField(
            model_name="group",
            name="master_project",
        ),
        migrations.RemoveField(
            model_name="host",
            name="master_project",
        ),
        migrations.RemoveField(
            model_name="inventory",
            name="master_project",
        ),
    ]
