# Generated by Django 2.2.12 on 2020-06-15 04:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_migrate_django_22'),
    ]

    operations = [
        migrations.AlterField(
            model_name='variable',
            name='value',
            field=models.TextField(null=True),
        ),
    ]
