# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-03 05:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_auto_20170502_2334'),
    ]

    operations = [
        migrations.AddField(
            model_name='typespermissions',
            name='periodic_tasks',
            field=models.ManyToManyField(blank=True, null=True, related_name='related_objects', to='main.PeriodicTask'),
        ),
        migrations.AddField(
            model_name='typespermissions',
            name='tasks',
            field=models.ManyToManyField(blank=True, null=True, related_name='related_objects', to='main.Task'),
        ),
    ]
