# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-17 04:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_history_task_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='Template',
            fields=[
                ('id', models.AutoField(max_length=20, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=512)),
                ('kind', models.CharField(max_length=32)),
                ('template_data', models.TextField(default='')),
            ],
        ),
        migrations.AlterIndexTogether(
            name='template',
            index_together=set([('id', 'name', 'kind')]),
        ),
    ]
