# Generated by Django 2.2.13 on 2020-06-22 06:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_auto_20200618_0818'),
    ]

    operations = [
        migrations.AddField(
            model_name='group',
            name='master_project',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='slave_group', to='main.Project'),
        ),
        migrations.AddField(
            model_name='host',
            name='master_project',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='slave_host', to='main.Project'),
        ),
        migrations.AddField(
            model_name='inventory',
            name='master_project',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='slave_inventory', to='main.Project'),
        ),
    ]
