# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-19 01:56
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_auto_20170717_1437'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='history',
            name='task_id',
        ),
    ]
