# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-05 00:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_auto_20170504_0810'),
    ]

    operations = [
        migrations.AddField(
            model_name='typespermissions',
            name='history',
            field=models.ManyToManyField(blank=True, null=True, related_name='related_objects', related_query_name='related_objects', to='main.History'),
        ),
    ]
