# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-21 04:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_remove_history_task_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='history',
            old_name='playbook',
            new_name='name',
        ),
        migrations.AddField(
            model_name='history',
            name='kind',
            field=models.CharField(default='PLAYBOOK', max_length=50),
        ),
        migrations.AlterIndexTogether(
            name='history',
            index_together=set([('id', 'project', 'name', 'status', 'inventory', 'start_time', 'stop_time')]),
        ),
    ]
