# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-24 01:39
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_auto_20170721_0441'),
    ]

    operations = [
        migrations.AlterField(
            model_name='history',
            name='project',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='history', related_query_name='history', to='main.Project'),
        ),
    ]
