# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-11 04:24
from __future__ import unicode_literals

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_typespermissions_history'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='status',
            field=models.CharField(default='NEW', max_length=32),
        ),
        migrations.AlterField(
            model_name='project',
            name='name',
            field=models.CharField(default=uuid.uuid1, max_length=512),
        ),
    ]
