# Generated by Django 3.2.12 on 2022-03-01 07:35

from django.db import migrations, models
import django.db.models.deletion
from ..models.base import ManyToManyFieldACL, ManyToManyFieldACLReverse


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_templateoption'),
    ]

    operations = [
        migrations.AlterField(
            model_name='group',
            name='acl',
            field=models.ManyToManyField(blank=True, related_name='groups', to='main.ACLPermission'),
        ),
        migrations.AlterField(
            model_name='group',
            name='master_project',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='slave_group', to='main.project'),
        ),
        migrations.AlterField(
            model_name='group',
            name='parents',
            field=ManyToManyFieldACLReverse(blank=True, related_name='groups', related_query_name='childrens', to='main.Group'),
        ),
        migrations.AlterField(
            model_name='host',
            name='acl',
            field=models.ManyToManyField(blank=True, related_name='hosts', to='main.ACLPermission'),
        ),
        migrations.AlterField(
            model_name='host',
            name='master_project',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='slave_host', to='main.project'),
        ),
        migrations.AlterField(
            model_name='inventory',
            name='acl',
            field=models.ManyToManyField(blank=True, related_name='inventories', to='main.ACLPermission'),
        ),
        migrations.AlterField(
            model_name='inventory',
            name='master_project',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='slave_inventory', to='main.project'),
        ),
        migrations.AlterField(
            model_name='periodictask',
            name='acl',
            field=models.ManyToManyField(blank=True, related_name='periodic_task', to='main.ACLPermission'),
        ),
        migrations.AlterField(
            model_name='project',
            name='acl',
            field=models.ManyToManyField(blank=True, related_name='projects', to='main.ACLPermission'),
        ),
        migrations.AlterField(
            model_name='project',
            name='groups',
            field=ManyToManyFieldACL(blank=True, related_name='projects', to='main.Group'),
        ),
        migrations.AlterField(
            model_name='project',
            name='hosts',
            field=ManyToManyFieldACL(blank=True, related_name='projects', to='main.Host'),
        ),
        migrations.AlterField(
            model_name='project',
            name='inventories',
            field=ManyToManyFieldACL(blank=True, related_name='projects', to='main.Inventory'),
        ),
        migrations.AlterField(
            model_name='template',
            name='acl',
            field=models.ManyToManyField(blank=True, related_name='template', to='main.ACLPermission'),
        ),
        migrations.AlterField(
            model_name='usergroup',
            name='acl',
            field=models.ManyToManyField(blank=True, to='main.ACLPermission'),
        ),
    ]
