# Generated by Django 3.2.12 on 2022-04-19 02:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0011_auto_20220301_0735'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='historylines',
            name='hidden',
        ),
        migrations.AlterField(
            model_name='historylines',
            name='id',
            field=models.BigAutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='historylines',
            name='line',
            field=models.TextField(default=''),
        ),
    ]
