# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-25 01:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0011_auto_20170724_0139'),
    ]

    operations = [
        migrations.RenameField(
            model_name='periodictask',
            old_name='playbook',
            new_name='mode',
        ),
        migrations.AddField(
            model_name='periodictask',
            name='kind',
            field=models.CharField(default='PLAYBOOK', max_length=50),
        ),
    ]
