# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-17 06:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0012_auto_20170513_0015'),
    ]

    operations = [
        migrations.AddField(
            model_name='group',
            name='parents',
            field=models.ManyToManyField(blank=True, null=True, related_name='groups', related_query_name='childrens', to='main.Group'),
        ),
        migrations.RemoveField(
            model_name='group',
            name='groups',
        ),
        migrations.AlterIndexTogether(
            name='group',
            index_together=set([('children',), ('children', 'id')]),
        ),
    ]
