# Generated by Django 3.2.14 on 2022-07-07 08:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0012_change_history_lines'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserSettings',
        ),
    ]
