# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-25 23:14
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0012_auto_20170725_0122'),
    ]

    operations = [
        migrations.AlterField(
            model_name='periodictask',
            name='project',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='periodic_tasks', related_query_name='periodic_tasks', to='main.Project'),
        ),
    ]
