# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-27 06:18
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0013_auto_20170725_2314'),
    ]

    operations = [
        migrations.RenameField(
            model_name='history',
            old_name='name',
            new_name='mode',
        ),
        migrations.AlterIndexTogether(
            name='history',
            index_together=set([('id', 'project', 'mode', 'status', 'inventory', 'start_time', 'stop_time')]),
        ),
    ]
