# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-08-14 06:44
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('main', '0014_auto_20170727_0618'),
    ]

    operations = [
        migrations.AddField(
            model_name='history',
            name='initiator',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='history', to=settings.AUTH_USER_MODEL),
        ),
    ]
