# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-23 02:29
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0014_periodictask_inventory'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='host',
            name='environment',
        ),
        migrations.DeleteModel(
            name='Environment',
        ),
    ]
