# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-08-14 07:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0014_auto_20170727_0618'),
    ]

    operations = [
        migrations.AddField(
            model_name='history',
            name='initiator',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='history',
            name='initiator_type',
            field=models.CharField(default='users', max_length=50),
        ),
        migrations.AlterIndexTogether(
            name='history',
            index_together=set([('id', 'project', 'mode', 'status', 'inventory', 'start_time', 'stop_time', 'initiator', 'initiator_type')]),
        ),
    ]
