# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-25 00:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0015_auto_20170814_1731'),
    ]

    operations = [
        migrations.AddField(
            model_name='typespermissions',
            name='template',
            field=models.ManyToManyField(blank=True, null=True, related_name='related_objects', related_query_name='related_objects', to='main.Template'),
        ),
    ]
