# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-04 03:12
from __future__ import unicode_literals

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0015_auto_20170623_0229'),
    ]

    operations = [
        migrations.AddField(
            model_name='periodictask',
            name='name',
            field=models.CharField(default=uuid.uuid1, max_length=512),
        ),
    ]
