# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-28 01:31
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0015_auto_20170623_0229'),
        ('main', '0016_auto_20170607_0551'),
    ]

    operations = [
    ]
