# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-04 04:23
from __future__ import unicode_literals

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0017_merge_20170704_1418'),
    ]

    operations = [
        migrations.AddField(
            model_name='history',
            name='raw_args',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='periodictask',
            name='name',
            field=models.CharField(default=uuid.uuid1, max_length=512),
        ),
        migrations.AlterField(
            model_name='history',
            name='raw_inventory',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='history',
            name='raw_stdout',
            field=models.TextField(default=''),
        ),
    ]
