# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-06 02:14
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0018_auto_20170704_1520'),
    ]

    operations = [
        migrations.CreateModel(
            name='HistoryLines',
            fields=[
                ('id', models.AutoField(max_length=20, primary_key=True, serialize=False)),
                ('line', models.TextField(default='')),
                ('line_number', models.IntegerField(default=0)),
            ],
            options={
                'default_related_name': 'raw_history_line',
            },
        ),
        migrations.RemoveField(
            model_name='history',
            name='raw_stdout',
        ),
        migrations.AddField(
            model_name='historylines',
            name='history',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='raw_history_line', related_query_name='raw_history_line', to='main.History'),
        ),
        migrations.AlterIndexTogether(
            name='historylines',
            index_together=set([('history',), ('line_number',), ('history', 'line_number')]),
        ),
    ]
