# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-31 04:00
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0019_auto_20171025_0104'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='aclpermission',
            unique_together=set([]),
        ),
    ]
