# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-06 07:28
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0019_auto_20170706_1214'),
        ('main', '0018_auto_20170704_1423'),
        ('main', '0016_periodictask_name'),
    ]

    operations = [
    ]
