# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-11-20 23:42
from __future__ import unicode_literals

from django.db import migrations, models
import uuid
from ..models.base import ManyToManyFieldACLReverse, ManyToManyFieldACL


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0024_migrate_templates'),
    ]

    operations = [
        migrations.CreateModel(
            name='Hook',
            fields=[
                ('id', models.AutoField(max_length=20, primary_key=True, serialize=False)),
                ('name', models.CharField(default=uuid.uuid1, max_length=512)),
                ('when', models.CharField(default=None, null=True, max_length=512)),
                ('type', models.CharField(max_length=32)),
                ('recipients', models.TextField()),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AlterField(
            model_name='group',
            name='parents',
            field=ManyToManyFieldACLReverse(blank=True, null=True, related_name='groups', related_query_name='childrens', to='main.Group'),
        ),
        migrations.AlterField(
            model_name='inventory',
            name='groups',
            field=ManyToManyFieldACL(related_name='inventories', to='main.Group'),
        ),
        migrations.AlterField(
            model_name='project',
            name='groups',
            field=ManyToManyFieldACL(blank=True, null=True, related_name='projects', to='main.Group'),
        ),
        migrations.AlterField(
            model_name='project',
            name='inventories',
            field=ManyToManyFieldACL(blank=True, null=True, related_name='projects', to='main.Inventory'),
        ),
    ]
