# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-22 01:45
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
from ..models.base import ForeignKeyACL


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0025_auto_20171120_1126'),
    ]

    operations = [
        migrations.RenameField(
            model_name='template',
            old_name='permissions',
            new_name='acl',
        ),
        migrations.RemoveField(
            model_name='group',
            name='permissions',
        ),
        migrations.RemoveField(
            model_name='host',
            name='permissions',
        ),
        migrations.RemoveField(
            model_name='inventory',
            name='permissions',
        ),
        migrations.RemoveField(
            model_name='periodictask',
            name='permissions',
        ),
        migrations.RemoveField(
            model_name='project',
            name='permissions',
        ),
        migrations.AddField(
            model_name='group',
            name='acl',
            field=models.ManyToManyField(blank=True, null=True, related_name='groups', to='main.ACLPermission'),
        ),
        migrations.AddField(
            model_name='host',
            name='acl',
            field=models.ManyToManyField(blank=True, null=True, related_name='hosts', to='main.ACLPermission'),
        ),
        migrations.AddField(
            model_name='inventory',
            name='acl',
            field=models.ManyToManyField(blank=True, null=True, related_name='inventories', to='main.ACLPermission'),
        ),
        migrations.AddField(
            model_name='periodictask',
            name='acl',
            field=models.ManyToManyField(blank=True, null=True, related_name='periodic_tasks', to='main.ACLPermission'),
        ),
        migrations.AddField(
            model_name='project',
            name='acl',
            field=models.ManyToManyField(blank=True, null=True, related_name='projects', to='main.ACLPermission'),
        ),
        migrations.AddField(
            model_name='usergroup',
            name='acl',
            field=models.ManyToManyField(blank=True, null=True, to='main.ACLPermission'),
        ),
        migrations.AlterField(
            model_name='hook',
            name='when',
            field=models.CharField(default=None, max_length=32, null=True),
        ),
        migrations.AlterField(
            model_name='template',
            name='project',
            field=ForeignKeyACL(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='main.Project'),
        ),
    ]
