# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-23 04:51
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion

def migrate_periodic_tasks(apps, schema_editor):
    PeriodicTask = apps.get_registered_model('main', 'PeriodicTask')
    PeriodicTask.objects.filter(project=None).delete()


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0026_auto_20171122_0145'),
    ]

    operations = [
        migrations.RunPython(migrate_periodic_tasks),
    ]
