# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-24 06:25
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0028_auto_20171123_0532'),
    ]

    operations = [
        migrations.RenameField(
            model_name='periodictask',
            old_name='inventory',
            new_name='_inventory',
        ),
        migrations.AddField(
            model_name='periodictask',
            name='inventory_file',
            field=models.CharField(blank=True, max_length=2048, null=True),
        ),
    ]
