# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-24 06:25
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0028_auto_20171123_0532'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='periodictask',
            name='inventory',
        ),
        migrations.AddField(
            model_name='periodictask',
            name='_inventory',
            field=models.ForeignKey(blank=True, db_column='inventory', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='periodic_tasks', related_query_name='periodic_tasks', to='main.Inventory'),
        ),
        migrations.AddField(
            model_name='periodictask',
            name='inventory_file',
            field=models.CharField(blank=True, max_length=2048, null=True),
        ),
    ]
