# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-27 08:01
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0029_auto_20171127_0801'),
    ]

    operations = [
        migrations.RenameField(
            model_name='periodictask',
            old_name='inventory',
            new_name='_inventory',
        ),
    ]
