# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-27 08:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0030_auto_20171127_0801'),
    ]

    operations = [
        migrations.AddField(
            model_name='periodictask',
            name='inventory_file',
            field=models.CharField(blank=True, max_length=2048, null=True),
        ),
    ]
