# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2017-12-08 02:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0031_periodictask_inventory_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='history',
            name='json_args',
            field=models.TextField(default='[]'),
        ),
    ]
