# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2017-12-13 02:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0033_auto_20171211_0732'),
    ]

    operations = [
        migrations.AddField(
            model_name='periodictask',
            name='enabled',
            field=models.BooleanField(default=True),
        ),
    ]
