# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-12-22 08:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0034_periodictask_enabled'),
    ]

    operations = [
        migrations.AddField(
            model_name='template',
            name='options_data',
            field=models.TextField(default=''),
        ),
    ]
