# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-02-26 00:50
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0035_usersettings'),
        ('main', '0035_template_options_data'),
    ]

    operations = [
    ]
