# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-04-17 02:46
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('main', '0037_auto_20180403_0113'),
    ]

    operations = [
        migrations.AddField(
            model_name='history',
            name='executor',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='history', to=settings.AUTH_USER_MODEL),
        ),
    ]
