# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-04-20 08:36
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
from ..models.base import first_staff_user


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0037_auto_20180403_0113'),
    ]

    operations = [
        migrations.AlterField(
            model_name='group',
            name='owner',
            field=models.ForeignKey(default=first_staff_user, on_delete=django.db.models.deletion.CASCADE, related_name='polemarch_group_set', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='host',
            name='owner',
            field=models.ForeignKey(default=first_staff_user, on_delete=django.db.models.deletion.CASCADE, related_name='polemarch_host_set', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='inventory',
            name='owner',
            field=models.ForeignKey(default=first_staff_user, on_delete=django.db.models.deletion.CASCADE, related_name='polemarch_inventory_set', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='periodictask',
            name='owner',
            field=models.ForeignKey(default=first_staff_user, on_delete=django.db.models.deletion.CASCADE, related_name='polemarch_periodictask_set', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='project',
            name='owner',
            field=models.ForeignKey(default=first_staff_user, on_delete=django.db.models.deletion.CASCADE, related_name='polemarch_project_set', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='template',
            name='owner',
            field=models.ForeignKey(default=first_staff_user, on_delete=django.db.models.deletion.CASCADE, related_name='polemarch_template_set', to=settings.AUTH_USER_MODEL),
        ),
    ]
