# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-04-20 09:08
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
from ..models.base import first_staff_user


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0038_auto_20180420_0836'),
    ]

    operations = [
        migrations.AddField(
            model_name='usergroup',
            name='hidden',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='usergroup',
            name='owner',
            field=models.ForeignKey(default=first_staff_user, on_delete=django.db.models.deletion.CASCADE, related_name='polemarch_usergroup_set', to=settings.AUTH_USER_MODEL),
        ),
    ]
