# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-04-19 05:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0039_migrate_history'),
    ]

    operations = [
        migrations.AddField(
            model_name='history',
            name='json_options',
            field=models.TextField(default='{}'),
        ),
    ]
