# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-05-04 03:59
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0041_auto_20180502_2355'),
        ('main', '0039_auto_20180420_0908'),
    ]

    operations = [
    ]
