# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-05-04 04:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0042_merge_20180504_0359'),
    ]

    operations = [
        migrations.AddField(
            model_name='usergroup',
            name='notes',
            field=models.TextField(default=''),
        ),
    ]
