# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-05-22 23:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0044_auto_20180515_0304'),
    ]

    operations = [
        migrations.AddField(
            model_name='hook',
            name='enable',
            field=models.BooleanField(default=True),
        ),
    ]
