# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-06-08 06:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0045_hook_enable'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historylines',
            name='line',
            field=models.CharField(default='', max_length=2048),
        ),
        migrations.AlterField(
            model_name='hook',
            name='recipients',
            field=models.CharField(max_length=30720),
        ),
        migrations.AlterField(
            model_name='template',
            name='options_data',
            field=models.TextField(default='{}'),
        ),
        migrations.AlterField(
            model_name='template',
            name='template_data',
            field=models.TextField(default='{}'),
        ),
    ]
