# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-06-08 02:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0045_hook_enable'),
    ]

    operations = [
        migrations.AlterField(
            model_name='group',
            name='notes',
            field=models.CharField(default='', max_length=4096),
        ),
        migrations.AlterField(
            model_name='history',
            name='json_args',
            field=models.CharField(default='{}', max_length=102400),
        ),
        migrations.AlterField(
            model_name='history',
            name='json_options',
            field=models.CharField(default='{}', max_length=102400),
        ),
        migrations.AlterField(
            model_name='history',
            name='raw_args',
            field=models.CharField(default='', max_length=102400),
        ),
        migrations.AlterField(
            model_name='history',
            name='raw_inventory',
            field=models.CharField(default='', max_length=4*1024*1024),
        ),
        migrations.AlterField(
            model_name='historylines',
            name='line',
            field=models.CharField(default='', max_length=2048),
        ),
        migrations.AlterField(
            model_name='hook',
            name='recipients',
            field=models.CharField(max_length=4096),
        ),
        migrations.AlterField(
            model_name='host',
            name='notes',
            field=models.CharField(default='', max_length=4096),
        ),
        migrations.AlterField(
            model_name='inventory',
            name='notes',
            field=models.CharField(default='', max_length=4096),
        ),
        migrations.AlterField(
            model_name='periodictask',
            name='notes',
            field=models.CharField(default='', max_length=4096),
        ),
        migrations.AlterField(
            model_name='project',
            name='notes',
            field=models.CharField(default='', max_length=4096),
        ),
        migrations.AlterField(
            model_name='template',
            name='notes',
            field=models.CharField(default='', max_length=4096),
        ),
        migrations.AlterField(
            model_name='template',
            name='options_data',
            field=models.CharField(default='{}', max_length=1048576),
        ),
        migrations.AlterField(
            model_name='template',
            name='template_data',
            field=models.CharField(default='{}', max_length=1048576),
        ),
        migrations.AlterField(
            model_name='usergroup',
            name='notes',
            field=models.CharField(default='', max_length=4096),
        ),
        migrations.AlterField(
            model_name='usersettings',
            name='settings',
            field=models.CharField(default='{}', max_length=1048576),
        ),
    ]
