# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-06-14 02:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0047_fix_templates'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='historylines',
            options={'ordering': ['-line_gnumber', '-line_number']},
        ),
        migrations.AddField(
            model_name='historylines',
            name='line_gnumber',
            field=models.IntegerField(default=0),
        ),
    ]
